variable "raspberrypi_ip" {}
variable "new_hostname" {}
variable "static_ip_and_mask" {}
variable "static_router" {}
variable "static_dns" {}
variable "new_user" {}
variable "new_user_uid" {}
variable "new_password" {}
variable "new_user_sshkey" {}
variable "timezone" {}
